apiVersion: v1
kind: Service
metadata:
  name: elastalert
  namespace: wazuh
  labels:
    app: elastalert
spec:
  ports:
  - port: 3030
  selector:
    app: elastalert
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: elastalert-deployment
  namespace: wazuh
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: elastalert
  template: 
    metadata: 
      labels: 
        app: elastalert
    spec: 
      containers: 
        - 
          image: harshalk91/elastalert:0.2.2
          imagePullPolicy: Always
          name: elastalert
          ports: 
            - 
              containerPort: 3030
              name: mainport
